### PR TITLE
build: added rollup build

### PR DESCRIPTION
**Pull request by codingJJJ**
添加rollup配置

### CODE REVIEW

**Comment by stevenleep** [comment]
> 添加rollup配置

add rollup build support to the project, you should use the commit type of `build` instead of `feat`;

You can refer to this article
https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/#build

**Comment by codingJJJ** [comment]
I was renamed the PR title,this commit can't remane because I has commit it already

**Comment by stevenleep** [comment]
CleanShot 2022-10-27 at 10 11 58@2x

One PR should focus on one thing. Rollup and Operations are two different things. 

It should be split into two PRs for submit！

**Comment by codingJJJ** [comment]
I was rolled back it

**Pull request merged**
